### ISSUE TITLE
Improve performance using complementary information of Gender

### ISSUE THREAD

**Issue by gokulkrshna** [mohammed-Emad/add_faces_to_svm_class#3]
Assuming that we always have Gender of every person added in the system, how to improve performance using this additional information of gender, training and testing time should reduce by half, what are your thoughts on this?

**Comment by mohammed-Emad** [comment]
Hi .. Firstly, I don’t understand what you mean by specifying a gender!
Do you mean that you use another system in parallel to recognize the type and then the face!
You described your problem with a higher test time ??
If your problem is implementation time, there are several solutions.
First, arbitrary steps such as reducing the dimensions of the tires, then reducing the size of the sliding windows or anchors! "The latter follows MTCNN" 
in lines [[L57]](https://github.com/davidsandberg/facenet/blob/master/src/align/align_dataset_mtcnn.py#L57)
[L58](https://github.com/davidsandberg/facenet/blob/master/src/align/align_dataset_mtcnn.py#L57)
[L59](https://github.com/davidsandberg/facenet/blob/master/src/align/align_dataset_mtcnn.py#L57)

Secondly, think about making use of the GPU
Parallel processing by making a side to identify the gender.
And another aspect to treat faces.
Both share a single stage Face detection system, MTCNN


Good luck

**Comment by gokulkrshna** [comment]
Most face-recognition systems will have  some sort of human intervention, in such scenarios , we can have gender as an additional parameter along with training faces or testing images. Can we not make use of this critical information ? Wouldn't it be better if we cluster dataset into gender groups ? Testing also would be faster if we only search on specific gender group.

**Comment by mohammed-Emad** [comment]
Yes, it can be divided according to type. This may help in obtaining a little more accurate detection in the real environment, in addition to the possibility of arranging and distributing in sections either arranged according to type, age group, etc.

But perhaps you will still need a type recognition form that is separate from people recognition.
Which means no change in test time. Maybe you should discuss these issues also on the original [repo,](https://github.com/davidsandberg/facenet) you find other solutions.
